CORPUS_DIR=$1
WORKING_DIR=$2
OUTPUT_DIR=$3
STARTTIMEPOINT=$4
ENDTIMEPOINT=$5
STEP=$6
FILTER_VOCAB_FILE=$7
WORKERS=$8
EXT=ngrams

mkdir -p $WORKING_DIR
mkdir -p $OUTPUT_DIR

mkdir -p $WORKING_DIR/posdist/
ls $CORPUS_DIR/*.$EXT | parallel -j${WORKERS} "python pos_tag.py -f {} -o $WORKING_DIR/posdist/{/.}.posdist"

detect_cp_pos.sh $WORKING_DIR/posdist/ $WORKING_DIR $OUTPUT_DIR $STARTTIMEPOINT $ENDTIMEPOINT $STEP $FILTER_VOCAB_FILE $WORKERS
